### ISSUE TITLE
Panic when using package level functions.

### ISSUE THREAD

**Issue by caiorcferreira** [americanas-go/log#31]
If someone used the package level functions, it would crash with a panic, like:
```go
import "github.com/americanas-go/log"

func main() {
  log.Info("Hello World") // this will panic
}
```

There is no documentation pointing that one should instantiate a `Logger` implementation and set it with `log.NewLogger`. **Even if this would be documented, having a package-level function panic because of lack of initialization is unacceptable**.

These functions should be noop or the lib should have a default implementation and rename the `log.NewLogger` to `log.SetGlobalLogger`. Also, with the current `log.NewLogger` is not concurrent-safe and it is impossible to derive what kind of behavior a client in the middle of a log operation would have if another goroutine changed the `Logger` implementation or even set it to `nil`.

Since Go was always an opinionated language and the community follows this approach, I believe that having a production-ready default `Logger` to allow safe and immediate use of the package-level functions is the best way to go. I think that using the `zap` implementation with `INFO` log level and JSON output is a reasonable default.

**Comment by caiorcferreira** [comment]
I can provide a PR if the proposed solution is accepted.

**Comment by jpfaria** [comment]
I agree with the idea. can send the PR.
